# Generated by Django 3.1 on 2020-08-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_character'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Character',
            new_name='Characters',
        ),
    ]
